version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=10001
    image: mia-app-java:1.0
    container_name: mia-app-container
    platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      - OLLAMA_HOST=http://ollama:11434
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    container_name: ollama-container
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    environment:
      - OLLAMA_MODEL=mistral
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        /bin/ollama serve &
        sleep 10
        /bin/ollama pull mistral
        wait
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  app_logs:
  app_data:
