spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      model: gemma3:1b
      options:
        temperature: 1.0
        top_p: 0.95
        top_k: 64
        repeat_penalty: 1.0
        num_ctx: 4096
        num_predict: 256
        stop: ["</s>", "USER:", "ASSISTANT:"]
        num_batch: 512
        num_gpu: 1
        num_thread: 8
        num_keep: 48
        seed: -1
        mirostat: 2
        mirostat_tau: 5.0
        mirostat_eta: 0.1
        rope_freq_base: 10000
        rope_freq_scale: 1.0
        num_gqa: 8
        rms_norm_eps: 1e-5
        logits_all: false
        vocab_only: false
        use_mmap: true
        use_mlock: false
        embedding: false
        rope_scaling:
          type: linear
          factor: 2.0
  datasource:
    url: jdbc:sqlite:data/test_generation.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

server:
  port: 8080

logging:
  level:
    com.example: INFO
 