spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      model: gemma3:1b
      options:
        temperature: 1.0
        top_p: 0.95
        top_k: 64
        repeat_penalty: 1.0
        num_ctx: 4096
        num_predict: 256
        stop: ["</s>", "USER:", "ASSISTANT:"]
        num_batch: 512
        num_gpu: 1
        num_thread: 8
        num_keep: 48
        seed: -1
        mirostat: 2
        mirostat_tau: 5.0
        mirostat_eta: 0.1
        rope_freq_base: 10000
        rope_freq_scale: 1.0
        num_gqa: 8
        rms_norm_eps: 1e-5
        logits_all: false
        vocab_only: false
        use_mmap: true
        use_mlock: false
        embedding: false
        rope_scaling:
          type: linear
          factor: 2.0
  datasource:
    url: jdbc:sqlite:data/test_generation.db?journal_mode=WAL&foreign_keys=on
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: false
      pool-name: SQLiteHikariCP
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: true

test:
  generation:
    max-attempts: 3
    acceptable-quality-levels:
      - QUALITY_HIGH
      - QUALITY_MEDIUM
    validation:
      base-prompt: |
        Validate UAT test cases quality. Use ONLY these exact keywords in responses:
        QUALITY_HIGH, QUALITY_MEDIUM, QUALITY_LOW
        SEVERITY_HIGH, SEVERITY_MEDIUM, SEVERITY_LOW
        
        Format response exactly as:
        
        OVERALL_QUALITY: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        
        METRICS:
        - Coherence: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        - Completeness: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        - Clarity: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        - TestData: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        - Coverage: [QUALITY_HIGH|QUALITY_MEDIUM|QUALITY_LOW]
        
        ISSUES:
        1. Type: [issue] 
           Severity: [SEVERITY_HIGH|SEVERITY_MEDIUM|SEVERITY_LOW]
           Fix: [suggestion]
           Impact: [brief description of the issue impact]
        
        RECOMMENDATIONS:
        1. [specific recommendation to improve test cases]
        2. [another recommendation]
      detailed-prompt: |
        Perform technical validation using ONLY these keywords:
        TECH_HIGH, TECH_MEDIUM, TECH_LOW
        RISK_HIGH, RISK_MEDIUM, RISK_LOW
        
        Format response exactly as:
        
        TECHNICAL_SCORE: [TECH_HIGH|TECH_MEDIUM|TECH_LOW]
        
        ASPECTS:
        - Coverage: [TECH_HIGH|TECH_MEDIUM|TECH_LOW]
        - ErrorHandling: [TECH_HIGH|TECH_MEDIUM|TECH_LOW]
        - Security: [TECH_HIGH|TECH_MEDIUM|TECH_LOW]
        
        RISKS:
        1. Area: [risk area]
           Level: [RISK_HIGH|RISK_MEDIUM|RISK_LOW]
           Action: [mitigation]
           Priority: [implementation priority]

server:
  port: 8080

logging:
  level:
    com.example: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
 