spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      model: gemma3:1b
      options:
        temperature: 1.0
        top_p: 0.95
        top_k: 64
        repeat_penalty: 1.0
        num_ctx: 4096
        num_predict: 256
        stop: ["</s>", "USER:", "ASSISTANT:"]
        num_batch: 512
        num_gpu: 1
        num_thread: 8
        num_keep: 48
        seed: -1
        mirostat: 2
        mirostat_tau: 5.0
        mirostat_eta: 0.1
        rope_freq_base: 10000
        rope_freq_scale: 1.0
        num_gqa: 8
        rms_norm_eps: 1e-5
        logits_all: false
        vocab_only: false
        use_mmap: true
        use_mlock: false
        embedding: false
        rope_scaling:
          type: linear
          factor: 2.0
  datasource:
    url: jdbc:sqlite:data/test_generation.db?journal_mode=WAL&foreign_keys=on
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: false
      pool-name: SQLiteHikariCP
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.example: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
 