spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      model: gemma3:4b
      options:
        temperature: 0.7
        top_p: 0.9
        top_k: 40
        num_predict: 256
        stop: ["</s>", "USER:", "ASSISTANT:"]
        num_ctx: 4096
        num_batch: 512
        num_gpu: 1
        num_thread: 8
        repeat_penalty: 1.1
        repeat_last_n: 64
        tfs_z: 1
        num_keep: 48
        seed: -1
        mirostat: 2
        mirostat_tau: 5.0
        mirostat_eta: 0.1
        rope_freq_base: 10000
        rope_freq_scale: 1.0
        num_gqa: 8
        rms_norm_eps: 1e-5
        logits_all: false
        vocab_only: false
        use_mmap: true
        use_mlock: false
        embedding: false
        rope_scaling:
          type: linear
          factor: 2.0
  datasource:
    url: jdbc:sqlite:test_generation.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    # hibernate:
    #   ddl-auto: update
    # show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true
    #     use_sql_comments: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
 